services:
  web:
    image: ghcr.io/real-ttx/matcms:latest
    pull_policy: always
    ports:
      - 9101:8080
    volumes:
      - matcms-data:/app/appdata
    networks:
      - main
    restart: unless-stopped

networks:
  main:
    external: true

volumes:
  matcms-data:
