// <auto-generated />
using System;
using MatCMS.Cloud.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MatCMS.Cloud.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260807195836_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("MatCMS.Cloud.Models.CloudSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("CloudSettings");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.Instance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("AppliedRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContainerId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .HasColumnType("TEXT");

                    b.Property<int>("Hosting")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageRef")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastHeartbeatUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastSyncError")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastSyncUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("LocalContainerName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LocalPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<bool>("OfflineNotified")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PageCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PluginCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProtocolVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UpdateNotifiedVersion")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("TokenHash");

                    b.ToTable("Instances");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.InstanceEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("InstanceId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Notified")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstanceId", "CreatedAt");

                    b.ToTable("InstanceEvents");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.Profile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActivateTemplateName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoApprove")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoUpdateLocal")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyOffline")
                        .HasColumnType("INTEGER");

                    b.Property<string>("NotifyRecipients")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NotifyUpdate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverwriteComponents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverwritePlugins")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverwriteSettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("OverwriteTemplates")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncComponents")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncPlugins")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncSettings")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncTemplates")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SyncUsers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("UseGlobalSmtp")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("JoinCode")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TemplateHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Type")
                        .IsUnique();

                    b.ToTable("ProfileComponents");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileGlobalUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("ProfileId", "UserId")
                        .IsUnique();

                    b.ToTable("ProfileGlobalUsers");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfilePlugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bundle")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Key")
                        .IsUnique();

                    b.ToTable("ProfilePlugins");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Key")
                        .IsUnique();

                    b.ToTable("ProfileSettings");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileStoreComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreComponentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreComponentId");

                    b.HasIndex("ProfileId", "StoreComponentId")
                        .IsUnique();

                    b.ToTable("ProfileStoreComponents");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileStorePlugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StorePluginId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StorePluginId");

                    b.HasIndex("ProfileId", "StorePluginId")
                        .IsUnique();

                    b.ToTable("ProfileStorePlugins");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileStoreTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StoreTemplateId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StoreTemplateId");

                    b.HasIndex("ProfileId", "StoreTemplateId")
                        .IsUnique();

                    b.ToTable("ProfileStoreTemplates");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AltBackground")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyFont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ButtonRadius")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ButtonStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerWidth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomCss")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomJs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderBackground")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderPadding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderTextColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadingColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadingFont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LayoutHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuMapJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Name")
                        .IsUnique();

                    b.ToTable("ProfileTemplates");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProfileId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "Username")
                        .IsUnique();

                    b.ToTable("ProfileUsers");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.StoreComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TemplateHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("StoreComponents");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.StorePlugin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bundle")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("StorePlugins");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.StoreTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AccentColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AltBackground")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyFont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ButtonRadius")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ButtonStyle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContainerWidth")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomCss")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomJs")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderBackground")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderPadding")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeaderTextColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadingColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadingFont")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LayoutHtml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MenuMapJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParamValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PartsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecondaryColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TextColor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("StoreTemplates");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.Instance", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.InstanceEvent", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Instance", "Instance")
                        .WithMany()
                        .HasForeignKey("InstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instance");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileComponent", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileGlobalUser", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatCMS.Cloud.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfilePlugin", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileSetting", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileStoreComponent", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatCMS.Cloud.Models.StoreComponent", "StoreComponent")
                        .WithMany()
                        .HasForeignKey("StoreComponentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("StoreComponent");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileStorePlugin", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatCMS.Cloud.Models.StorePlugin", "StorePlugin")
                        .WithMany()
                        .HasForeignKey("StorePluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("StorePlugin");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileStoreTemplate", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MatCMS.Cloud.Models.StoreTemplate", "StoreTemplate")
                        .WithMany()
                        .HasForeignKey("StoreTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");

                    b.Navigation("StoreTemplate");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileTemplate", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("MatCMS.Cloud.Models.ProfileUser", b =>
                {
                    b.HasOne("MatCMS.Cloud.Models.Profile", "Profile")
                        .WithMany()
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Profile");
                });
#pragma warning restore 612, 618
        }
    }
}
